from __future__ import annotations

from mcpmap.models import AnalysisResult, Finding, Severity

_SEVERITY_ICON = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH: "HIGH",
    Severity.MEDIUM: "MEDIUM",
    Severity.LOW: "LOW",
    Severity.INFO: "INFO",
}

_SEVERITY_BADGE = {
    Severity.CRITICAL: "![CRITICAL](https://img.shields.io/badge/CRITICAL-dc2626?style=flat-square)",
    Severity.HIGH: "![HIGH](https://img.shields.io/badge/HIGH-ea580c?style=flat-square)",
    Severity.MEDIUM: "![MEDIUM](https://img.shields.io/badge/MEDIUM-ca8a04?style=flat-square)",
    Severity.LOW: "![LOW](https://img.shields.io/badge/LOW-16a34a?style=flat-square)",
    Severity.INFO: "![INFO](https://img.shields.io/badge/INFO-6b7280?style=flat-square)",
}


class MarkdownReporter:
    def __init__(self, ascii_mode: bool = False):
        self.ascii_mode = ascii_mode

    def _badge(self, severity: Severity) -> str:
        return _SEVERITY_ICON[severity] if self.ascii_mode else _SEVERITY_BADGE[severity]

    def render(self, results: list[AnalysisResult]) -> str:
        lines: list[str] = []

        total_findings = sum(len(r.findings) for r in results)
        total_critical = sum(r.stats.get("CRITICAL", 0) for r in results)
        total_high = sum(r.stats.get("HIGH", 0) for r in results)
        total_medium = sum(r.stats.get("MEDIUM", 0) for r in results)
        total_low = sum(r.stats.get("LOW", 0) for r in results)

        lines.append("# mcpmap — AI Agent Attack Surface Report\n")
        lines.append("## Summary\n")
        lines.append(f"| Scanned Files | CRITICAL | HIGH | MEDIUM | LOW | Total |")
        lines.append(f"|---|---|---|---|---|---|")
        lines.append(f"| {len(results)} | {total_critical} | {total_high} | {total_medium} | {total_low} | {total_findings} |\n")

        if not results or total_findings == 0:
            lines.append("No findings detected.\n")
            return "\n".join(lines)

        lines.append("## Findings by File\n")

        for result in results:
            if not result.findings:
                lines.append(f"### `{result.target}` — No findings\n")
                continue

            lines.append(f"### `{result.target}`\n")
            lines.append(f"Format: `{result.format}` | "
                         f"CRITICAL: {result.stats.get('CRITICAL', 0)} | "
                         f"HIGH: {result.stats.get('HIGH', 0)} | "
                         f"MEDIUM: {result.stats.get('MEDIUM', 0)} | "
                         f"LOW: {result.stats.get('LOW', 0)}\n")

            for finding in result.findings:
                lines.append(f"---\n")
                tags = ""
                if finding.is_new:
                    tags += " `NEW`"
                if finding.suppressed:
                    tags += " `SUPPRESSED`"
                lines.append(
                    f"#### {self._badge(finding.severity)} [{finding.rule_id}] {finding.rule_name}{tags}\n"
                )
                lines.append(f"**Category:** {finding.category}\n")
                lines.append(f"**Location:** `{finding.location}`\n")
                lines.append(f"**Evidence:** {finding.evidence}\n")
                lines.append(f"**Description:** {finding.description}\n")
                lines.append(f"**Remediation:** {finding.remediation}\n")
                if finding.suppressed and finding.suppression_reason:
                    lines.append(f"**Suppression reason:** {finding.suppression_reason}\n")

                if finding.owasp_llm:
                    refs = " | ".join(
                        f"[{o.id}: {o.name}]({o.url})" for o in finding.owasp_llm
                    )
                    lines.append(f"**OWASP LLM Top 10:** {refs}\n")

                if finding.mitre_atlas:
                    refs = " | ".join(
                        f"[{m.id}: {m.name}]({m.url})" for m in finding.mitre_atlas
                    )
                    lines.append(f"**MITRE ATLAS:** {refs}\n")

        lines.append("\n---")
        lines.append("*Generated by [mcpmap](https://github.com/bogdanticu88/mcpmap)*\n")
        return "\n".join(lines)
